option('lib_type', type: 'combo', choices: ['shared', 'static'], value: 'shared',
       description: 'How to build the slang lib')

option('slang_llvm_flavor', type: 'combo',
       choices: ['fetch_binary', 'fetch_binary_if_possible', 'use_system_llvm', 'disable'],
       value: 'fetch_binary_if_possible',
       description: 'How to get or build slang-llvm')

option('spirv', type: 'feature', value: 'enabled',
       description: 'Enable SPIR-V backend support')
option('dx12', type: 'feature', value: 'enabled',
       description: 'Enable DirectX 12 backend support')
option('metal', type: 'feature', value: 'enabled',
       description: 'Enable Metal backend support')
