option('deprecation_warnings',
    choices : ['default', 'error', 'no-error', 'ignore'],
    type : 'combo',
    description : 'Treatment of deprecation warnings'
)

option('enable_tests',
    type: 'feature',
    description: 'Build various test programs'
)

option('have_sdl_thread_support',
    type: 'boolean',
    value: true,
    description: 'Use SDL threads for multi-threading'
)

option('triplet',
    type: 'string',
    value: '',
    description : 'Rust target triplet (if needed)'
)

option('rustc-version',
    type: 'string',
    value: '',
    description : 'Minimum Rust compiler version (if needed)'
)

option('slang_dir',
    type: 'string',
    value: '',
    description: 'Slang installation directory'
)

option('slang_include_dir',
    type: 'string',
    value: '',
    description: 'Slang include directory'
)

option('slang_lib_dir',
    type: 'string',
    value: '',
    description: 'Slang library directory'
)

option('allocator',
	type: 'combo',
	choices: ['custom', 'default'],
	value: 'default',
	description: 'Choose whether to use the default memory allocator or manually manage memory allocation'
)

option('need_mimalloc',
	type: 'boolean',
	value: true,
	description: 'Whether mimalloc is a required allocator'
)

option(
    'renderer_metal',
    type : 'feature',
    value : 'auto',
    description : 'Build the Metal renderer API'
)

option(
    'renderer_wgpu',
    type : 'feature',
    value : 'auto',
    description : 'Build the WebGPU renderer API'
)

option(
    'renderer_default',
    type : 'combo',
    value : 'auto',
    choices : ['auto', 'metal', 'wgpu'],
    description : 'Which renderer API to use by default'
)

option('fastnoiselite',
    type: 'boolean',
    value: false,
    description: 'Enable the FastNoiseLite dependency'
)

option(
    'audio_sdl',
    type : 'feature',
    value : 'auto',
    description : 'Build the SDL audio backend'
)

option(
    'audio_null',
    type : 'feature',
    value : 'auto',
    description : 'Build the no-op audio backend (silence); you want this on!'
)

option(
    'audio_default',
    type : 'combo',
    choices : ['auto', 'sdl', 'null'],
    description : 'Which audio backend to use by default'
)

option(
	'support_opus_files',
	type : 'feature',
	value : 'auto',
	description : 'Build the Opus backend to allow Opus files'
)

option(
    'tests',
    type : 'feature',
    description : 'Build various test programs'
)
