[constants]
# To be overridden
ldflags_macos = []

[built-in options]
werror = true
debug = true
strip = true
default_library = 'static'
prefer_static = true

[project options]
tests = 'enabled'

[cglm:built-in options]
default_library = 'static'
werror = false

[fastnoiselite:built-in options]
werror = false

[mimalloc:built-in options]
werror = false

[mimalloc-cmake-wrapper:built-in options]
werror = false

[opus:built-in options]
default_library = 'static'
werror = false

[opusfile:built-in options]
default_library = 'static'
werror = false

[sdl3:built-in options]
werror = false

[sdl3-cmake-wrapper:built-in options]
werror = false

[sokol:built-in options]
werror = false

[spoopy-slang-wrapper:built-in options]
werror = false

[cglm:project options]
install = false
build_tests = false

[opus:project options]
docs = 'disabled'
extra-programs = 'disabled'
tests = 'disabled'
