[constants]
# To be overridden if needed
ldflags_macos = []

[built-in options]
werror = true
debug = true
strip = true

[project options]
tests = 'enabled'

[cglm:built-in options]
werror = false

[fastnoiselite:built-in options]
werror = false

[mimalloc:built-in options]
werror = false

[mimalloc-cmake-wrapper:built-in options]
werror = false

[opus:built-in options]
werror = false

[opusfile:built-in options]
werror = false

[sdl3:built-in options]
werror = false

[sdl3-cmake-wrapper:built-in options]
werror = false

[sokol:built-in options]
werror = false

[spoopy-slang-wrapper:built-in options]
werror = false
