kore_inc_dirs = include_directories(
	  '../include/kore2',
	  '../../../include',
	  '../kore/Sources',
	  '../kore/Backends/System/Apple/Sources',
	  '../kore/Backends/System/macOS/Sources',
	  '../kore/Backends/System/POSIX/Sources',
	  '../kore/Backends/Graphics5/Metal/Sources',
	  '../kore/Backends/Graphics4/G4onG5/Sources'
)

kore_c_args = [
	  '-Wno-unused-variable',
	  '-Wno-unused-function',
	  '-Wno-unused-parameter',
	  '-Wno-deprecated-declarations',
	  '-Wno-sign-compare',
	  '-Wno-format-security',
	  '-Wno-incompatible-pointer-types',
	  '-Wno-implicit-function-declaration',
	  '-Wno-gnu-folding-constant',
	  '-Wno-macro-redefined',
	  '-Wno-unguarded-availability-new',
	  '-Wno-return-mismatch',
	  '-Wno-int-conversion',
	  '-Wno-missing-braces',
	  '-Wno-unused-but-set-variable',
	  '-Wno-format',
	  '-Wno-switch',
	  '-DKINC_NO_MAIN',
	  '-DKINC_NO_KORE',
	  '-DKINC_G1',
	  '-DKORE_G1',
	  '-DKINC_G2',
	  '-DKORE_G2',
	  '-DKINC_G3',
	  '-DKORE_G3',
	  '-DKINC_A1',
	  '-DKORE_A1',
	  '-DKINC_A2',
	  '-DKORE_A2',
	  '-DKINC_LZ4X',
	  '-DKORE_LZ4X',
	  '-DKINC_METAL',
	  '-DKORE_METAL',
	  '-DKINC_G4',
	  '-DKORE_G4',
	  '-DKINC_G5',
	  '-DKORE_G5',
	  '-DKINC_G4ONG5',
	  '-DKORE_G4ONG5',
	  '-DKORE_NO_MAIN',
	  '-DNDEBUG',
]

kore_cpp_args = [
	  '-Wno-unused-variable',
	  '-Wno-unused-function',
	  '-Wno-unused-parameter',
	  '-Wno-deprecated-declarations',
	  '-Wno-sign-compare',
	  '-Wno-format-security',
	  '-Wno-incompatible-pointer-types',
	  '-Wno-implicit-function-declaration',
	  '-Wno-gnu-folding-constant',
	  '-Wno-macro-redefined',
	  '-Wno-unguarded-availability-new',
	  '-Wno-return-mismatch',
	  '-Wno-int-conversion',
	  '-Wno-missing-braces',
	  '-Wno-unused-but-set-variable',
	  '-Wno-format',
	  '-Wno-switch',
	  '-DKINC_NO_MAIN',
	  '-DKINC_NO_KORE',
	  '-DKINC_G1',
	  '-DKORE_G1',
	  '-DKINC_G2',
	  '-DKORE_G2',
	  '-DKINC_G3',
	  '-DKORE_G3',
	  '-DKINC_A1',
	  '-DKORE_A1',
	  '-DKINC_A2',
	  '-DKORE_A2',
	  '-DKINC_LZ4X',
	  '-DKORE_LZ4X',
	  '-DKINC_METAL',
	  '-DKORE_METAL',
	  '-DKINC_G4',
	  '-DKORE_G4',
	  '-DKINC_G5',
	  '-DKORE_G5',
	  '-DKINC_G4ONG5',
	  '-DKORE_G4ONG5',
	  '-DKORE_NO_MAIN',
	  '-DNDEBUG',
]

sources = [
	  '../src/kore2/kore2.c',
	  '../src/kore2/spoopy_kinc_shader.c',
	  '../src/kore2/spoopy_kinc_pipeline.c',
	  '../src/kore2/spoopy_video.c',
	  '../kore/Backends/Graphics4/G4onG5/Sources/kinc/backend/graphics4/g4ong5unit.c',
	  '../kore/Backends/Graphics5/Metal/Sources/kinc/backend/graphics5/metalunit.m',
	  '../kore/Backends/System/Apple/Sources/kinc/backend/appleunit.m',
	  '../kore/Backends/System/POSIX/Sources/kinc/backend/posixunit.c',
	  '../kore/Backends/System/macOS/Sources/kinc/backend/macosunit.m',
	  '../kore/Sources/kinc/rootunit.c',
	  '../kore/Sources/kinc/audio1/a1unit.c',
	  '../kore/Sources/kinc/audio2/audio.c',
	  '../kore/Sources/kinc/graphics1/graphics.c',
	  '../kore/Sources/kinc/graphics2/graphics_soft.c',
	  '../kore/Sources/kinc/graphics4/g4unit.c',
	  '../kore/Sources/kinc/graphics5/g5unit.c',
	  '../kore/Sources/kinc/input/inputunit.c',
	  '../kore/Sources/kinc/io/iounit.c',
	  '../kore/Sources/kinc/libs/stb_vorbis.c',
	  '../kore/Sources/kinc/math/mathunit.c',
	  '../kore/Sources/kinc/network/networkunit.c',
]

target_files = sources

add_languages('objc', native: false)

kore_objc_args = [
	  '-fobjc-arc',
]

dependencies = [
	  dependency('Metal'),
	  dependency('MetalKit'),
	  dependency('IOKit'),
	  dependency('Cocoa'),
	  dependency('AppKit'),
	  dependency('CoreAudio'),
	  dependency('CoreData'),
	  dependency('CoreMedia'),
	  dependency('CoreVideo'),
	  dependency('AVFoundation'),
	  dependency('Foundation'),
]

spoopy_renderer = library('spoopy_renderer',
	  target_files,
	  include_directories : kore_inc_dirs,
	  c_args : kore_c_args,
	  cpp_args : kore_cpp_args,
	  objc_args : [kore_objc_args] + kore_c_args,
	  dependencies : dependencies,
	  install : false
)
